language: php
php: 
    - 5.3
    - 5.4
    - 5.5

before_script:
    - curl -s http://getcomposer.org/install | php
    - php composer.phar install 

script: 
    - cd DataTablesBundle/Tests/
    - phpunit . 
